### ISSUE TITLE
KeyError: 'train_weight'

### ISSUE THREAD

**Issue by Dinxin** [guyulongcs/CIKM2020_DMT#1]
![image](https://user-images.githubusercontent.com/19572535/97269263-346a9e00-1868-11eb-93d9-bc765482104d.png)

**Comment by Dinxin** [comment]
项目中没有默认的demo.conf配置文件，项目中给出的唯一一个.conf文件中没有train_weight这个选项。

**Comment by guyulongcs** [comment]
Thank you for your interest in our work. I have fixed this problem.
