### ISSUE TITLE
about bias feature

### ISSUE THREAD

**Issue by weiguozhao** [guyulongcs/CIKM2020_DMT#2]
请教一下，线上serve的时候**bias feature**是如何获取的？

因为线上serve构造特征的时候，预测当前target没办法获取下一个index或page的内容的吧？

**Comment by guyulongcs** [comment]
Thank you for your interest in our work. 
This question can be answered in Section 4.5 in our paper.
In the online prediction stage, we didn't use the Bias Deep Neural Network or the bias features. We directly use the utility scores for ranking. 
You can think the bias features and bias score are both 0 simply.
