### ISSUE TITLE
some files not found

### ISSUE THREAD

**Issue by Felix1990** [guyulongcs/CIKM2020_DMT#3]
Hello , I am reading your code and find some files not found.
I did not find "export_model_imp" and "export_embed_mlp_recall" in saved_model dictionary. "tower_batch_features" in run_dnn.py  is also missing.
Looking forward your reply. Thank you!

**Comment by guyulongcs** [comment]
Thanks. "export_model_imp" and "export_embed_mlp_recall are not used in this paper. "tower_batch_features" is defined in line 152 in run_dnn.py. The code should be executed in GPU.
