### ISSUE TITLE
Sharing python requirements file

### ISSUE THREAD

**Issue by nidhinkrishnanv** [guyulongcs/CIKM2020_DMT#6]
Can you please share the python requirements file?

**Comment by guyulongcs** [comment]
The code was tested on Linux machine with several GPUs (NVIDIA Tesla P40). The tensorflow version is 1.12. I have left the company, and cannot provide the detail requirements information in the machine. Thanks!

**Comment by LinaZhang** [comment]
> The code was tested on Linux machine with several GPUs (NVIDIA Tesla P40). The tensorflow version is 1.12. I have left the company, and cannot provide the detail requirements information in the machine. Thanks!

The python requirements is very hard to build. I have try to build it for 2 days but fails.
